require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/entity_groups', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # EntityGroup. As you add validations to EntityGroup, be sure to
  # adjust the attributes here as well.
  # let(:valid_attributes) do
  #   skip('Add a hash of attributes valid for your model')
  # end

  # let(:invalid_attributes) do
  #   skip('Add a hash of attributes invalid for your model')
  # end

  describe 'GET /index' do
    it 'renders a successful response' do
      EntityGroup.create! valid_attributes
      get entity_groups_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      entity_group = EntityGroup.create! valid_attributes
      get entity_group_url(entity_group)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_entity_group_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      entity_group = EntityGroup.create! valid_attributes
      get edit_entity_group_url(entity_group)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new EntityGroup' do
        expect do
          post entity_groups_url, params: { entity_group: valid_attributes }
        end.to change(EntityGroup, :count).by(1)
      end

      it 'redirects to the created entity_group' do
        post entity_groups_url, params: { entity_group: valid_attributes }
        expect(response).to redirect_to(entity_group_url(EntityGroup.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new EntityGroup' do
        expect do
          post entity_groups_url, params: { entity_group: invalid_attributes }
        end.to change(EntityGroup, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post entity_groups_url, params: { entity_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      # let(:new_attributes) do
      #   skip('Add a hash of attributes valid for your model')
      # end

      # it 'updates the requested entity_group' do
      #   entity_group = EntityGroup.create! valid_attributes
      #   patch entity_group_url(entity_group), params: { entity_group: new_attributes }
      #   entity_group.reload
      #   skip('Add assertions for updated state')
      # end

      it 'redirects to the entity_group' do
        entity_group = EntityGroup.create! valid_attributes
        patch entity_group_url(entity_group), params: { entity_group: new_attributes }
        entity_group.reload
        expect(response).to redirect_to(entity_group_url(entity_group))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        entity_group = EntityGroup.create! valid_attributes
        patch entity_group_url(entity_group), params: { entity_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested entity_group' do
      entity_group = EntityGroup.create! valid_attributes
      expect do
        delete entity_group_url(entity_group)
      end.to change(EntityGroup, :count).by(-1)
    end

    it 'redirects to the entity_groups list' do
      entity_group = EntityGroup.create! valid_attributes
      delete entity_group_url(entity_group)
      expect(response).to redirect_to(entity_groups_url)
    end
  end
end
